# Generated by Django 4.0.4 on 2022-06-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='photo',
        ),
    ]
