# Generated by Django 4.0.4 on 2022-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_remove_registration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(default=True, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
