# Generated by Django 4.0.4 on 2022-06-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_registration_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
